version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/troumaca-web-be-server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/unzip-resource-bundle.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
