version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Troumaca-web-server
hooks:
  BeforeInstall:
    - location: scripts/install-packages.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/check_deployment.sh
      timeout: 300
      runas: ec2-user
