version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build-ts
  post_build:
    commands:
      - cp appspec.yml dist
      - cp -r node_modules dist
      - cp -r scripts dist
      - cp properties.file dist
      - cp -r nedb dist
      - cd dist
      - zip -qr troumaca-web-be.zip *
      - cd ..
      - echo Build completed on `date`
artifacts:
    files:
#      - dist/appspec.yml
      - dist/troumaca-web-be.zip
#      - dist/scripts/*
#        - '**/*'
#    base-directory: 'dist*'
    discard-paths: yes
