version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build-ts
  post_build:
    commands:
      - mkdir troumaca-web-be
      - cp appspec.yml troumaca-web-be
      - cp -r node_modules troumaca-web-be
      - cp -r scripts troumaca-web-be
      - cp -r nedb troumaca-web-be
      - cp -r dist troumaca-web-be
      - cd troumaca-web-be
      - zip -qr troumaca-web-be.zip *
      - cd ..
      - echo Build completed on `date`
artifacts:
    files:
#      - dist/appspec.yml
      - troumaca-web-be/troumaca-web-be.zip
#      - dist/scripts/*
#        - '**/*'
#    base-directory: 'dist*'
    discard-paths: yes
