/** Declaration file generated by dts-gen */

export = header_case_normalizer;

declare function header_case_normalizer(header: any): any;

declare namespace header_case_normalizer {
    const prototype: {};
}

